[project]
name = "name-shrinker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.18.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
    "types-pyinstaller",
]
